package com.pojo;
// Generated 21 Sep, 2019 2:43:36 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	private Integer bid;
	private String bookId;
	private String bookname;
	private String authorName;
	private Double price;
	private Set orders = new HashSet(0);

	public Books() {
	}

	public Books(String bookId, String bookname, String authorName, Double price, Set orders) {
		this.bookId = bookId;
		this.bookname = bookname;
		this.authorName = authorName;
		this.price = price;
		this.orders = orders;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
