package com.pojo;
// Generated 21 Sep, 2019 2:43:36 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer oid;
	private Books books;
	private Register register;
	private String orderId;
	private Date orderDate;

	public Order() {
	}

	public Order(Books books, Register register, String orderId, Date orderDate) {
		this.books = books;
		this.register = register;
		this.orderId = orderId;
		this.orderDate = orderDate;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Books getBooks() {
		return this.books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

	public Register getRegister() {
		return this.register;
	}

	public void setRegister(Register register) {
		this.register = register;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
